### ISSUE TITLE
Error when trying to compile.

### ISSUE THREAD

**Issue by Astrea0014** [weak1337/R6FullExpFarmer#4]
I get these two errors when trying to compile the project:
Error (active)	E0167	argument of type "const char *" is incompatible with parameter of type "LPCWSTR"	ccExpFarmer	C:\Users\USERNAME\Desktop\R6FullExpFarmer-master\ccExpFarmer\main.cpp	6
And:
Error (active)	E0167	argument of type "const char *" is incompatible with parameter of type "LPCWSTR"	ccExpFarmer	C:\Users\USERNAME\Desktop\R6FullExpFarmer-master\ccExpFarmer\main.cpp	6

**Comment by weak1337** [comment]
Multibyte

**Comment by Astrea0014** [comment]
What does that mean

**Comment by Astrea0014** [comment]
Ive solved it now apparently
